// exprforge/emitters/csharp.js
const Emitter = require("./base.js");

function fn1(name) {
    return ([x]) => `Math.${name}(${x})`;
}

function fn2(name) {
    return ([a, b]) => `Math.${name}(${a}, ${b})`;
}

function capitalize(s) {
    return s.charAt(0).toUpperCase() + s.slice(1);
}

// NOT just capitalize(fn.name): C# forbids a member from sharing its
// enclosing type's exact name (CS0542), unlike Java, which permits a
// same-named non-constructor method. Fine as long as capitalize() changes
// the name (e.g. "fibonacci" -> "Fibonacci"), but every AST-author name
// that's already capitalized (e.g. this project's SpEf-prefixed samples)
// makes capitalize() a no-op -- class and method end up identical, a real
// compile error confirmed against a real sample, not a hypothetical.
function wrapperClassName(fnName) {
    return `${capitalize(fnName)}Impl`;
}

const emitter = new Emitter({
    ext: "cs",
    // Always suffixed with d: a bare integer-valued literal like `5` is a
    // C# int by default, and int/int is integer division -- silently
    // wrong if both operands of a div() ever happened to be int-valued
    // literals. The suffix forces double everywhere, no exceptions,
    // rather than only suffixing the cases that would otherwise break.
    formatNumber: (v) => `${v}d`,
    calls: {
        sqrt: fn1("Sqrt"), abs: fn1("Abs"), sin: fn1("Sin"), cos: fn1("Cos"), tan: fn1("Tan"),
        asin: fn1("Asin"), acos: fn1("Acos"), atan: fn1("Atan"), log: fn1("Log"),
        log2: fn1("Log2"), log10: fn1("Log10"), exp: fn1("Exp"), floor: fn1("Floor"),
        ceil: fn1("Ceiling"), trunc: fn1("Truncate"),
        pow: fn2("Pow"), atan2: fn2("Atan2"), min: fn2("Min"), max: fn2("Max"),
        // Math.Sign returns int, not double -- our AST is float64-only throughout.
        sign: ([x]) => `((double) Math.Sign(${x}))`,
        // .NET's Math.Round(double) ties to EVEN ("banker's rounding") by
        // default, NOT this project's standardized round-half-AWAY-from-
        // zero convention -- see js.js's own comment and the root
        // README's "round() at exact .5 boundaries" section. Math.Sign
        // returns int, which promotes to double automatically in this
        // multiplication -- no explicit cast needed the way the sign:
        // entry above needs one on its own (there, the WHOLE expression
        // needs to already read as a double, since nothing else in it is).
        round: ([x]) => `(Math.Sign(${x}) * Math.Floor(Math.Abs(${x}) + 0.5))`,
        // No Math.Hypot in .NET -- same manual formula as QB64's/C's.
        hypot: ([a, b]) => `Math.Sqrt((${a}) * (${a}) + (${b}) * (${b}))`,
        wrapIndex: ([i, m]) => `(((${i} % ${m}) + ${m}) % ${m})`,
        // Math.Clamp (.NET Core 2.0+) is a direct stdlib match for
        // clampIndex's semantics -- no hand-built max(lo, min(hi, i))
        // needed here, unlike most other targets.
        clampIndex: ([i, lo, hi]) => `Math.Clamp(${i}, ${lo}, ${hi})`,
    },
    // C# array indexing requires an integral index type, not double.
    emitIndex: function (targetNode, atNode) {
        return `${this.emitExpr(targetNode)}[(int)(${this.emitExpr(atNode)})]`;
    },
    // C# has a native ?: ternary, same syntax as JS/C/Java -- no override
    // needed, this is exactly what base.js's default already emits.
    formatFunction: (fn, body, letBindings = []) => {
        const params = fn.params.map((p) => `${fn.paramTypes?.[p] === "number[]" ? "double[]" : "double"} ${p}`).join(", ");
        const lets = letBindings.map(({ name, valueStr }) => `        double ${name} = ${valueStr};`).join("\n");
        const letsBlock = lets ? lets + "\n" : "";
        return `// AUTO-GENERATED by ExprForge -- do not hand-edit.\n` +
               `public static class ${wrapperClassName(fn.name)}\n` +
               `{\n` +
               `    public static double ${fn.name}(${params})\n` +
               `    {\n` +
               letsBlock +
               `        return ${body};\n` +
               `    }\n` +
               `}\n`;
    },
    // Multiple named outputs from one call: a native C# value tuple with
    // named elements -- real field access (result.rx) with no wrapper
    // type to declare, and (unlike Go's named returns) no risk of
    // colliding with a same-named let binding, since a tuple literal's
    // element names aren't pre-declared locals in the method body.
    formatSuite: (fn, outputStrs, letBindings = []) => {
        const params = fn.params.map((p) => `${fn.paramTypes?.[p] === "number[]" ? "double[]" : "double"} ${p}`).join(", ");
        const lets = letBindings.map(({ name, valueStr }) => `        double ${name} = ${valueStr};`).join("\n");
        const letsBlock = lets ? lets + "\n" : "";
        const outputNames = Object.keys(outputStrs);
        const returnType = `(${outputNames.map((n) => `double ${n}`).join(", ")})`;
        const returnExpr = `(${outputNames.map((n) => `${n}: ${outputStrs[n]}`).join(", ")})`;
        return `// AUTO-GENERATED by ExprForge -- do not hand-edit.\n` +
               `public static class ${wrapperClassName(fn.name)}\n` +
               `{\n` +
               `    public static ${returnType} ${fn.name}(${params})\n` +
               `    {\n` +
               letsBlock +
               `        return ${returnExpr};\n` +
               `    }\n` +
               `}\n`;
    },
});

module.exports = emitter;
