// exprforge/emitters/go.js
const Emitter = require("./base.js");

function fn1(name) {
    return ([x]) => `math.${name}(${x})`;
}

function fn2(name) {
    return ([a, b]) => `math.${name}(${a}, ${b})`;
}

const emitter = new Emitter({
    ext: "go",
    formatNumber: (v) => (Number.isInteger(v) ? `${v}.0` : String(v)),
    calls: {
        sqrt: fn1("Sqrt"), abs: fn1("Abs"), sin: fn1("Sin"), cos: fn1("Cos"), tan: fn1("Tan"),
        asin: fn1("Asin"), acos: fn1("Acos"), atan: fn1("Atan"), log: fn1("Log"),
        log2: fn1("Log2"), log10: fn1("Log10"), exp: fn1("Exp"), floor: fn1("Floor"),
        ceil: fn1("Ceil"), round: fn1("Round"), trunc: fn1("Trunc"),
        pow: fn2("Pow"), atan2: fn2("Atan2"), min: fn2("Min"), max: fn2("Max"), hypot: fn2("Hypot"),
        sign: ([x]) => `math.Copysign(1, ${x})`,
    },
    formatFunction: (fn, body) => {
        const params = fn.params.map((p) => `${p} float64`).join(", ");
        return `// AUTO-GENERATED by ExprForge -- do not hand-edit.\n` +
               `package splinegen\n\n` +
               `import "math"\n\n` +
               `func ${capitalize(fn.name)}(${params}) float64 {\n` +
               `\treturn ${body}\n` +
               `}\n`;
    },
});

function capitalize(s) {
    return s.charAt(0).toUpperCase() + s.slice(1);
}

module.exports = emitter;
