// exprforge/emitters/java.js
const Emitter = require("./base.js");

function fn1(name) {
    return ([x]) => `Math.${name}(${x})`;
}

function fn2(name) {
    return ([a, b]) => `Math.${name}(${a}, ${b})`;
}

const emitter = new Emitter({
    ext: "java",
    formatNumber: (v) => (Number.isInteger(v) ? `${v}.0` : String(v)),
    calls: {
        sqrt: fn1("sqrt"), abs: fn1("abs"), sin: fn1("sin"), cos: fn1("cos"), tan: fn1("tan"),
        asin: fn1("asin"), acos: fn1("acos"), atan: fn1("atan"), log: fn1("log"),
        log10: fn1("log10"), exp: fn1("exp"), floor: fn1("floor"), ceil: fn1("ceil"),
        signum: fn1("signum"),
        pow: fn2("pow"), atan2: fn2("atan2"), min: fn2("min"), max: fn2("max"), hypot: fn2("hypot"),
        // Math has no log2; Java also lacks round-to-double and trunc directly.
        log2: ([x]) => `(Math.log(${x}) / Math.log(2.0))`,
        round: ([x]) => `((double) Math.round(${x}))`,
        trunc: ([x]) => `(double) (long) (${x})`,
        sign: fn1("signum"),
    },
    formatFunction: (fn, body, letBindings = []) => {
        const params = fn.params.map((p) => `double ${p}`).join(", ");
        const lets = letBindings.map(({ name, valueStr }) => `        double ${name} = ${valueStr};`).join("\n");
        const letsBlock = lets ? lets + "\n" : "";
        return `// AUTO-GENERATED by ExprForge -- do not hand-edit.\n` +
               `public final class ${capitalize(fn.name)} {\n` +
               `    private ${capitalize(fn.name)}() {\n` +
               `    }\n\n` +
               `    public static double ${fn.name}(${params}) {\n` +
               letsBlock +
               `        return ${body};\n` +
               `    }\n` +
               `}\n`;
    },
    // Multiple named outputs from one call: Java has no native multi-return,
    // so this nests a small immutable Result class inside the same
    // top-level class every function here already gets, keeping everything
    // in the one per-function file this project's output layout assumes.
    formatSuite: (fn, outputStrs, letBindings = []) => {
        const params = fn.params.map((p) => `double ${p}`).join(", ");
        const lets = letBindings.map(({ name, valueStr }) => `        double ${name} = ${valueStr};`).join("\n");
        const letsBlock = lets ? lets + "\n" : "";
        const outputNames = Object.keys(outputStrs);
        const fields = outputNames.map((n) => `        public final double ${n};`).join("\n");
        const ctorParams = outputNames.map((n) => `double ${n}`).join(", ");
        const ctorAssigns = outputNames.map((n) => `            this.${n} = ${n};`).join("\n");
        const newArgs = outputNames.map((n) => outputStrs[n]).join(", ");
        return `// AUTO-GENERATED by ExprForge -- do not hand-edit.\n` +
               `public final class ${capitalize(fn.name)} {\n` +
               `    private ${capitalize(fn.name)}() {\n` +
               `    }\n\n` +
               `    public static final class Result {\n` +
               `${fields}\n\n` +
               `        Result(${ctorParams}) {\n` +
               `${ctorAssigns}\n` +
               `        }\n` +
               `    }\n\n` +
               `    public static Result ${fn.name}(${params}) {\n` +
               letsBlock +
               `        return new Result(${newArgs});\n` +
               `    }\n` +
               `}\n`;
    },
});

function capitalize(s) {
    return s.charAt(0).toUpperCase() + s.slice(1);
}

module.exports = emitter;
