// exprforge/emitters/java.js
const Emitter = require("./base.js");

function fn1(name) {
    return ([x]) => `Math.${name}(${x})`;
}

function fn2(name) {
    return ([a, b]) => `Math.${name}(${a}, ${b})`;
}

const emitter = new Emitter({
    ext: "java",
    // Same real bug class as c.js's formatNumber (see its comment): once
    // JS's own String() renders an integer-valued number in exponential
    // form (huge magnitudes, e.g. 1e250), unconditionally appending ".0"
    // produces "1e+250.0" -- not valid Java (a decimal point can't
    // follow the exponent part of a Java floating-point literal; the
    // fraction has to come BEFORE it, e.g. "1.0e250"). An already-
    // exponential string is already an unambiguous Java double literal
    // on its own.
    formatNumber: (v) => {
        const s = String(v);
        if (/e/i.test(s)) return s;
        return Number.isInteger(v) ? `${s}.0` : s;
    },
    calls: {
        sqrt: fn1("sqrt"), abs: fn1("abs"), sin: fn1("sin"), cos: fn1("cos"), tan: fn1("tan"),
        asin: fn1("asin"), acos: fn1("acos"), atan: fn1("atan"), log: fn1("log"),
        log10: fn1("log10"), exp: fn1("exp"), floor: fn1("floor"), ceil: fn1("ceil"),
        signum: fn1("signum"),
        pow: fn2("pow"), atan2: fn2("atan2"), min: fn2("min"), max: fn2("max"), hypot: fn2("hypot"),
        // Math has no log2; Java also lacks round-to-double and trunc directly.
        log2: ([x]) => `(Math.log(${x}) / Math.log(2.0))`,
        // Math.round ties toward +Infinity, NOT this project's standardized
        // round-half-AWAY-from-zero convention -- see js.js's own comment
        // and the root README's "round() at exact .5 boundaries" section.
        // Math.signum already returns double for a double argument, so no
        // cast is needed here the way the plain Math.round path above did.
        round: ([x]) => `(Math.signum(${x}) * Math.floor(Math.abs(${x}) + 0.5))`,
        trunc: ([x]) => `(double) (long) (${x})`,
        sign: fn1("signum"),
        wrapIndex: ([i, m]) => `(((${i} % ${m}) + ${m}) % ${m})`,
        clampIndex: ([i, lo, hi]) => `Math.max(${lo}, Math.min(${hi}, ${i}))`,
    },
    // Java array indexing requires int, not double -- no implicit
    // narrowing conversion exists for this.
    emitIndex: function (targetNode, atNode) {
        return `${this.emitExpr(targetNode)}[(int)(${this.emitExpr(atNode)})]`;
    },
    formatFunction: (fn, body, letBindings = [], guardLines = [], opts = {}) => {
        const params = fn.params.map((p) => `${fn.paramTypes?.[p] === "number[]" ? "double[]" : "double"} ${p}`).join(", ");
        const lets = letBindings.map(({ name, valueStr }) => `        double ${name} = ${valueStr};`).join("\n");
        const letsBlock = lets ? lets + "\n" : "";
        // opts.publicClass (default true, so today's single-function-
        // per-file output is byte-for-byte unchanged unless a caller
        // opts out): Java allows at most ONE public top-level type per
        // file, and it must be named after the file -- confirmed
        // directly (a real javac) that concatenating N of this class's
        // own always-public wrapper classes into one .java file is a
        // hard compile error ("class F2 is public, should be declared
        // in a file named F2.java"), the same duplicate/conflicting-
        // preamble bug class reported for QB64's own SAFE_MATH_HELPERS
        // -- structurally different from every other target's fix here
        // (there's no shared block to include once; EVERY function
        // still needs its own class, full stop), so this is its own
        // opt, not opts.includeHelpers. Dropping "public" (package-
        // private) is enough: confirmed directly that multiple
        // non-public top-level classes coexist in one file with no
        // restriction, and are still fully callable from any other
        // class in the same file/package (which is exactly the
        // situation a consumer concatenating functions to use TOGETHER
        // is already in) -- only cross-PACKAGE access is what "public"
        // actually buys here. See docs/multi-function-files.md.
        const classModifier = opts.publicClass === false ? "final" : "public final";
        return `// AUTO-GENERATED by ExprForge -- do not hand-edit.\n` +
               `${classModifier} class ${capitalize(fn.name)} {\n` +
               `    private ${capitalize(fn.name)}() {\n` +
               `    }\n\n` +
               `    public static double ${fn.name}(${params}) {\n` +
               letsBlock +
               `        return ${body};\n` +
               `    }\n` +
               `}\n`;
    },
    // Multiple named outputs from one call: Java has no native multi-return,
    // so this nests a small immutable Result class inside the same
    // top-level class every function here already gets, keeping everything
    // in the one per-function file this project's output layout assumes.
    formatSuite: (fn, outputStrs, letBindings = [], guardLines = [], opts = {}) => {
        const params = fn.params.map((p) => `${fn.paramTypes?.[p] === "number[]" ? "double[]" : "double"} ${p}`).join(", ");
        const lets = letBindings.map(({ name, valueStr }) => `        double ${name} = ${valueStr};`).join("\n");
        const letsBlock = lets ? lets + "\n" : "";
        const outputNames = Object.keys(outputStrs);
        const fields = outputNames.map((n) => `        public final double ${n};`).join("\n");
        const ctorParams = outputNames.map((n) => `double ${n}`).join(", ");
        const ctorAssigns = outputNames.map((n) => `            this.${n} = ${n};`).join("\n");
        const newArgs = outputNames.map((n) => outputStrs[n]).join(", ");
        // See formatFunction's own comment above -- same opts.publicClass.
        const classModifier = opts.publicClass === false ? "final" : "public final";
        return `// AUTO-GENERATED by ExprForge -- do not hand-edit.\n` +
               `${classModifier} class ${capitalize(fn.name)} {\n` +
               `    private ${capitalize(fn.name)}() {\n` +
               `    }\n\n` +
               `    public static final class Result {\n` +
               `${fields}\n\n` +
               `        Result(${ctorParams}) {\n` +
               `${ctorAssigns}\n` +
               `        }\n` +
               `    }\n\n` +
               `    public static Result ${fn.name}(${params}) {\n` +
               letsBlock +
               `        return new Result(${newArgs});\n` +
               `    }\n` +
               `}\n`;
    },
});

function capitalize(s) {
    return s.charAt(0).toUpperCase() + s.slice(1);
}

module.exports = emitter;
