// exprforge/emitters/js.js
const Emitter = require("./base.js");

function fn1(name) {
    return ([x]) => `Math.${name}(${x})`;
}

function fn2(name) {
    return ([a, b]) => `Math.${name}(${a}, ${b})`;
}

const emitter = new Emitter({
    ext: "js",
    formatNumber: (v) => String(v),
    calls: {
        sqrt: fn1("sqrt"), abs: fn1("abs"), sin: fn1("sin"), cos: fn1("cos"), tan: fn1("tan"),
        asin: fn1("asin"), acos: fn1("acos"), atan: fn1("atan"), log: fn1("log"),
        log2: fn1("log2"), log10: fn1("log10"), exp: fn1("exp"), floor: fn1("floor"),
        ceil: fn1("ceil"), round: fn1("round"), trunc: fn1("trunc"), sign: fn1("sign"),
        pow: fn2("pow"), atan2: fn2("atan2"), min: fn2("min"), max: fn2("max"), hypot: fn2("hypot"),
        // See primitives.js's own comment -- the double-application
        // ((i % m) + m) % m is self-correcting regardless of which sign
        // convention `%` follows, so it's used uniformly across every
        // target here rather than trusting each language's own convention
        // from memory alone.
        wrapIndex: ([i, m]) => `(((${i} % ${m}) + ${m}) % ${m})`,
        clampIndex: ([i, lo, hi]) => `Math.max(${lo}, Math.min(${hi}, ${i}))`,
    },
    // No cast needed: JS's bracket notation converts a numeric key to a
    // string (String(2.0) === "2"), which matches a real array element's
    // own string-keyed property name -- confirmed reliable, not just
    // assumed. Array params need no type annotation either (JS has none),
    // so no formatFunction/formatSuite change was needed for this at all.
    emitIndex: function (targetNode, atNode) {
        return `${this.emitExpr(targetNode)}[${this.emitExpr(atNode)}]`;
    },
    formatFunction: (fn, body, letBindings = []) => {
        const lets = letBindings.map(({ name, valueStr }) => `    const ${name} = ${valueStr};`).join("\n");
        const letsBlock = lets ? lets + "\n" : "";
        return `// AUTO-GENERATED by ExprForge — do not hand-edit.\n` +
               `function ${fn.name}(${fn.params.join(", ")}) {\n` +
               letsBlock +
               `    return ${body};\n` +
               `}\n\n` +
               `module.exports = { ${fn.name} };\n`;
    },
    // Multiple named outputs from one call: a plain object literal, JS's
    // native idiom for this — no new type needed.
    formatSuite: (fn, outputStrs, letBindings = []) => {
        const lets = letBindings.map(({ name, valueStr }) => `    const ${name} = ${valueStr};`).join("\n");
        const letsBlock = lets ? lets + "\n" : "";
        const fields = Object.entries(outputStrs)
            .map(([name, valueStr]) => `        ${name}: ${valueStr},`)
            .join("\n");
        return `// AUTO-GENERATED by ExprForge — do not hand-edit.\n` +
               `function ${fn.name}(${fn.params.join(", ")}) {\n` +
               letsBlock +
               `    return {\n${fields}\n    };\n` +
               `}\n\n` +
               `module.exports = { ${fn.name} };\n`;
    },
});

module.exports = emitter;
