// exprforge/emitters/js.js
const Emitter = require("./base.js");

function fn1(name) {
    return ([x]) => `Math.${name}(${x})`;
}

function fn2(name) {
    return ([a, b]) => `Math.${name}(${a}, ${b})`;
}

const emitter = new Emitter({
    ext: "js",
    formatNumber: (v) => String(v),
    calls: {
        sqrt: fn1("sqrt"), abs: fn1("abs"), sin: fn1("sin"), cos: fn1("cos"), tan: fn1("tan"),
        asin: fn1("asin"), acos: fn1("acos"), atan: fn1("atan"), log: fn1("log"),
        log2: fn1("log2"), log10: fn1("log10"), exp: fn1("exp"), floor: fn1("floor"),
        ceil: fn1("ceil"), round: fn1("round"), trunc: fn1("trunc"), sign: fn1("sign"),
        pow: fn2("pow"), atan2: fn2("atan2"), min: fn2("min"), max: fn2("max"), hypot: fn2("hypot"),
    },
    formatFunction: (fn, body) => (
        `// AUTO-GENERATED by ExprForge — do not hand-edit.\n` +
        `function ${fn.name}(${fn.params.join(", ")}) {\n` +
        `    return ${body};\n` +
        `}\n\n` +
        `module.exports = { ${fn.name} };\n`
    ),
});

module.exports = emitter;
