// exprforge/emitters/js.js
const Emitter = require("./base.js");

function fn1(name) {
    return ([x]) => `Math.${name}(${x})`;
}

function fn2(name) {
    return ([a, b]) => `Math.${name}(${a}, ${b})`;
}

const emitter = new Emitter({
    ext: "js",
    formatNumber: (v) => String(v),
    calls: {
        sqrt: fn1("sqrt"), abs: fn1("abs"), sin: fn1("sin"), cos: fn1("cos"), tan: fn1("tan"),
        asin: fn1("asin"), acos: fn1("acos"), atan: fn1("atan"), log: fn1("log"),
        log2: fn1("log2"), log10: fn1("log10"), exp: fn1("exp"), floor: fn1("floor"),
        ceil: fn1("ceil"), trunc: fn1("trunc"), sign: fn1("sign"),
        // Math.round ties toward +Infinity (round(-0.5) === -0, round(-1.5)
        // === -1) -- NOT the convention this project standardizes round()
        // on everywhere (round half AWAY from zero, matching the majority
        // of this project's 18 targets -- see the root README's "round()
        // at exact .5 boundaries" section for the full, directly-verified
        // breakdown of why this convention specifically). Built from
        // Math.sign/Math.floor/Math.abs, which already agree with every
        // other target unconditionally.
        round: ([x]) => `(Math.sign(${x}) * Math.floor(Math.abs(${x}) + 0.5))`,
        pow: fn2("pow"), atan2: fn2("atan2"), min: fn2("min"), max: fn2("max"), hypot: fn2("hypot"),
        // See primitives.js's own comment -- the double-application
        // ((i % m) + m) % m is self-correcting regardless of which sign
        // convention `%` follows, so it's used uniformly across every
        // target here rather than trusting each language's own convention
        // from memory alone.
        wrapIndex: ([i, m]) => `(((${i} % ${m}) + ${m}) % ${m})`,
        clampIndex: ([i, lo, hi]) => `Math.max(${lo}, Math.min(${hi}, ${i}))`,
    },
    // No cast needed: JS's bracket notation converts a numeric key to a
    // string (String(2.0) === "2"), which matches a real array element's
    // own string-keyed property name -- confirmed reliable, not just
    // assumed. Array params need no type annotation either (JS has none),
    // so no formatFunction/formatSuite change was needed for this at all.
    emitIndex: function (targetNode, atNode) {
        return `${this.emitExpr(targetNode)}[${this.emitExpr(atNode)}]`;
    },
    // Opt-in only (see emitFunction's `addTypeGuards` and
    // docs/runtime-type-guards.md) -- JS has no compile-time type
    // checking at all, so this is the one guard against a caller passing
    // a plain number where an array was declared.
    typeGuard: (p, fnName) => `if (!Array.isArray(${p})) throw new Error(${JSON.stringify(`${fnName}: "${p}" must be an array`)});`,
    // Opt-in on top of typeGuard's own opt-in (see emitFunction's
    // `fn.arrayLengths` doc comment in base.js) -- runs after the type
    // guard above, so `${p}.length` is always safe to read here.
    lengthGuard: (p, lenP, fnName) =>
        `if (${p}.length !== ${lenP}) throw new Error(${JSON.stringify(`${fnName}: "${p}".length must equal "${lenP}"`)});`,
    formatFunction: (fn, body, letBindings = [], guardLines = []) => {
        const guards = guardLines.map((l) => `    ${l}`).join("\n");
        const guardsBlock = guards ? guards + "\n" : "";
        const lets = letBindings.map(({ name, valueStr }) => `    const ${name} = ${valueStr};`).join("\n");
        const letsBlock = lets ? lets + "\n" : "";
        return `// AUTO-GENERATED by ExprForge — do not hand-edit.\n` +
               `function ${fn.name}(${fn.params.join(", ")}) {\n` +
               guardsBlock +
               letsBlock +
               `    return ${body};\n` +
               `}\n\n` +
               `module.exports = { ${fn.name} };\n`;
    },
    // Multiple named outputs from one call: a plain object literal, JS's
    // native idiom for this — no new type needed.
    formatSuite: (fn, outputStrs, letBindings = [], guardLines = []) => {
        const guards = guardLines.map((l) => `    ${l}`).join("\n");
        const guardsBlock = guards ? guards + "\n" : "";
        const lets = letBindings.map(({ name, valueStr }) => `    const ${name} = ${valueStr};`).join("\n");
        const letsBlock = lets ? lets + "\n" : "";
        const fields = Object.entries(outputStrs)
            .map(([name, valueStr]) => `        ${name}: ${valueStr},`)
            .join("\n");
        return `// AUTO-GENERATED by ExprForge — do not hand-edit.\n` +
               `function ${fn.name}(${fn.params.join(", ")}) {\n` +
               guardsBlock +
               letsBlock +
               `    return {\n${fields}\n    };\n` +
               `}\n\n` +
               `module.exports = { ${fn.name} };\n`;
    },
});

module.exports = emitter;
