// exprforge/emitters/julia.js
const Emitter = require("./base.js");

function fn1(name) {
    return ([x]) => `${name}(${x})`;
}

function fn2(name) {
    return ([a, b]) => `${name}(${a}, ${b})`;
}

const emitter = new Emitter({
    ext: "jl",
    // Julia accepts JS-style numeric literal syntax directly, including
    // exponential notation ("1e-9") -- no suffix or conversion needed.
    formatNumber: (v) => String(v),
    calls: {
        // All 22 are Julia Base functions -- no import, no derivation, no
        // wrapping needed for any of them, unlike every other target here.
        sqrt: fn1("sqrt"), abs: fn1("abs"), sin: fn1("sin"), cos: fn1("cos"), tan: fn1("tan"),
        asin: fn1("asin"), acos: fn1("acos"), atan: fn1("atan"), atan2: fn2("atan"),
        log: fn1("log"), log2: fn1("log2"), log10: fn1("log10"), exp: fn1("exp"),
        pow: ([x, y]) => `(${x} ^ ${y})`,
        floor: fn1("floor"), ceil: fn1("ceil"), trunc: fn1("trunc"),
        min: fn2("min"), max: fn2("max"), hypot: fn2("hypot"),
        // Julia's round() defaults to round-half-to-even (banker's
        // rounding), not the round-half-away-from-zero every other target
        // here uses -- RoundNearestTiesAway asks for that explicitly.
        // Doesn't affect the conformance suite either way (it deliberately
        // avoids exact .5 boundaries, see test/conformance.test.js), but
        // this is the genuinely-matching behavior, not just the
        // untested-so-it-doesn't-matter one.
        round: ([x]) => `round(${x}, RoundNearestTiesAway)`,
        // Julia does have sign(), and sign(0.0) == 0.0 -- matches every
        // other target's zero-aware convention already, so no need to
        // build this one by hand (unlike most other emitters here).
        sign: fn1("sign"),
    },
    // Julia's ?: is exactly base.js's default ternary -- no override needed.
    formatFunction: (fn, body, letBindings = []) => {
        const params = fn.params.join(", ");
        const lets = letBindings.map(({ name, valueStr }) => `    ${name} = ${valueStr}`).join("\n");
        const letsBlock = lets ? lets + "\n" : "";
        return `# AUTO-GENERATED by ExprForge -- do not hand-edit.\n` +
               `function ${fn.name}(${params})\n` +
               letsBlock +
               `    return ${body}\n` +
               `end\n`;
    },
    // Multiple named outputs from one call: Julia's native named tuple
    // (`(rx=..., ry=...)`, dot access at the call site) -- the same idiom
    // C#'s emitter uses, and needs no wrapper type declared up front.
    formatSuite: (fn, outputStrs, letBindings = []) => {
        const params = fn.params.join(", ");
        const lets = letBindings.map(({ name, valueStr }) => `    ${name} = ${valueStr}`).join("\n");
        const letsBlock = lets ? lets + "\n" : "";
        const outputNames = Object.keys(outputStrs);
        const returnExpr = outputNames.map((n) => `${n}=${outputStrs[n]}`).join(", ");
        return `# AUTO-GENERATED by ExprForge -- do not hand-edit.\n` +
               `function ${fn.name}(${params})\n` +
               letsBlock +
               `    return (${returnExpr})\n` +
               `end\n`;
    },
});

module.exports = emitter;
