// exprforge/emitters/lua.js
const Emitter = require("./base.js");

function fn1(name) {
    return ([x]) => `math.${name}(${x})`;
}

function fn2(name) {
    return ([a, b]) => `math.${name}(${a}, ${b})`;
}

const emitter = new Emitter({
    ext: "lua",
    // Lua accepts JS-style numeric literal syntax directly, including
    // exponential notation ("1e-9") -- no suffix or conversion needed.
    // Integer-valued literals may be Lua's integer subtype (5.3+), but
    // that's safe here: every bin op comes from ast.js's own +-*/ set,
    // and Lua's `/` is always true (float) division regardless of
    // operand types, unlike C#'s int/int trap.
    formatNumber: (v) => String(v),
    calls: {
        sqrt: fn1("sqrt"), abs: fn1("abs"), sin: fn1("sin"), cos: fn1("cos"), tan: fn1("tan"),
        asin: fn1("asin"), acos: fn1("acos"), atan: fn1("atan"), exp: fn1("exp"),
        min: fn2("min"), max: fn2("max"),
        // Lua 5.3+ removed math.atan2 -- math.atan(y, x) with a second
        // argument is the replacement.
        atan2: fn2("atan"),
        // Lua 5.3+ removed math.pow -- ^ is the exponentiation operator
        // (always float-producing, like / ).
        pow: ([x, y]) => `(${x} ^ ${y})`,
        // math.log takes an optional base -- covers log/log2/log10 in one
        // function rather than three.
        log: fn1("log"),
        log2: ([x]) => `math.log(${x}, 2)`,
        log10: ([x]) => `math.log(${x}, 10)`,
        // math.floor/math.ceil return Lua's integer subtype (5.3+), not
        // float -- +0.0 coerces back, matching this project's float64-only
        // model everywhere else.
        floor: ([x]) => `(math.floor(${x}) + 0.0)`,
        ceil: ([x]) => `(math.ceil(${x}) + 0.0)`,
        // No math.round in Lua at any version -- the standard manual idiom
        // (floor(x+0.5)) matches JS's/Java's round-half-up convention, not
        // C/Go/Rust's round-half-away-from-zero -- same already-documented,
        // already-avoided-in-tests divergence as elsewhere in this project,
        // not a new one.
        round: ([x]) => `(math.floor(${x} + 0.5) + 0.0)`,
        // No math.trunc either -- math.modf(x) returns (integral,
        // fractional) parts as its two results; parenthesizing the call
        // selects just the first (Lua's standard idiom for narrowing a
        // multi-return to one value), which is exactly trunc(x), and
        // already float-typed.
        trunc: ([x]) => `(math.modf(${x}))`,
        // No math.sign either. Lua's and/or conditional idiom is safe here
        // specifically because only nil/false are falsy in Lua -- 0.0 (or
        // any number) is always truthy, unlike JS/Python/C. Zero-aware by
        // construction (see Go's/Rust's sign() history in this project for
        // what happens when it isn't).
        sign: ([x]) => `((${x} > 0) and 1.0 or ((${x} < 0) and -1.0 or 0.0))`,
        // No math.hypot in Lua's standard library at any version.
        hypot: ([a, b]) => `math.sqrt((${a}) * (${a}) + (${b}) * (${b}))`,
    },
    // Lua has no ?: ternary. `cond and a or b` is the standard idiom --
    // safe here for the same reason sign() above is: every value in this
    // AST is a number, and only nil/false are ever falsy in Lua, so `a`
    // (the then-branch) is never mistaken for "falsy" regardless of its
    // numeric value (unlike this same idiom in some other languages).
    emitSelect: function (condNode, thenStr, elseStr) {
        const L = this.emitExpr(condNode.left);
        const R = this.emitExpr(condNode.right);
        return `((${L} ${condNode.op} ${R}) and (${thenStr}) or (${elseStr}))`;
    },
    formatFunction: (fn, body, letBindings = []) => {
        const params = fn.params.join(", ");
        const lets = letBindings.map(({ name, valueStr }) => `    local ${name} = ${valueStr}`).join("\n");
        const letsBlock = lets ? lets + "\n" : "";
        return `-- AUTO-GENERATED by ExprForge -- do not hand-edit.\n` +
               `function ${fn.name}(${params})\n` +
               letsBlock +
               `    return ${body}\n` +
               `end\n`;
    },
    // Multiple named outputs from one call: Lua's native multiple return
    // values -- the cleanest of any target here, no wrapper type and no
    // collision risk (unlike Go's named returns, `local` declarations in
    // the body and the trailing `return` list are entirely separate
    // namespaces). A leading comment documents the order, since Lua's
    // returns are positional, not named, at the call site.
    formatSuite: (fn, outputStrs, letBindings = []) => {
        const params = fn.params.join(", ");
        const lets = letBindings.map(({ name, valueStr }) => `    local ${name} = ${valueStr}`).join("\n");
        const letsBlock = lets ? lets + "\n" : "";
        const outputNames = Object.keys(outputStrs);
        const returnStmt = outputNames.map((n) => outputStrs[n]).join(", ");
        return `-- AUTO-GENERATED by ExprForge -- do not hand-edit.\n` +
               `-- Returns (${outputNames.join(", ")}).\n` +
               `function ${fn.name}(${params})\n` +
               letsBlock +
               `    return ${returnStmt}\n` +
               `end\n`;
    },
});

module.exports = emitter;
