// exprforge/emitters/perl.js
const Emitter = require("./base.js");

function fn1(name) {
    return ([x]) => `${name}(${x})`;
}

function posix1(name) {
    return ([x]) => `POSIX::${name}(${x})`;
}

// Every scalar variable reference in Perl needs a leading `$` -- unlike
// every other emitter here, base.js's default "var" case (bare
// `node.name`) is wrong for every single reference, not just declarations.
// Emitter is a real class (see base.js), so this overrides just the one
// case and defers to the base class for everything else, instead of
// needing a new config hook shared by every other emitter.
class PerlEmitter extends Emitter {
    emitExpr(node) {
        if (node.type === "var") return `$${node.name}`;
        return super.emitExpr(node);
    }
}

const emitter = new PerlEmitter({
    ext: "pl",
    // Perl accepts JS-style numeric literal syntax directly, including
    // exponential notation ("1e-9") -- no suffix or conversion needed.
    formatNumber: (v) => String(v),
    calls: {
        // Core builtins -- no module needed.
        sqrt: fn1("sqrt"), abs: fn1("abs"), sin: fn1("sin"), cos: fn1("cos"),
        exp: fn1("exp"), log: fn1("log"), atan2: ([a, b]) => `atan2(${a}, ${b})`,
        pow: ([x, y]) => `(${x} ** ${y})`,
        // Everything else Perl core doesn't have is in the POSIX module --
        // called fully-qualified (POSIX::name) rather than imported, so
        // there's no import list to keep in sync with this table and no
        // risk of a POSIX symbol shadowing a core builtin of the same name.
        tan: posix1("tan"), asin: posix1("asin"), acos: posix1("acos"), atan: posix1("atan"),
        log10: posix1("log10"), floor: posix1("floor"), ceil: posix1("ceil"),
        round: posix1("round"), trunc: posix1("trunc"),
        hypot: ([a, b]) => `POSIX::hypot(${a}, ${b})`,
        // No log2 anywhere in core or POSIX -- derive it.
        log2: ([x]) => `(log(${x}) / log(2))`,
        // List::Util, same fully-qualified convention as POSIX above.
        min: ([a, b]) => `List::Util::min(${a}, ${b})`,
        max: ([a, b]) => `List::Util::max(${a}, ${b})`,
        // No sign() anywhere in core, POSIX, or List::Util -- build it
        // directly. Zero-aware by construction (see Go's/Rust's sign()
        // history in this project for what happens when it isn't).
        sign: ([x]) => `(${x} > 0 ? 1.0 : (${x} < 0 ? -1.0 : 0.0))`,
    },
    // Perl's ?: is exactly base.js's default ternary -- no override needed.
    formatFunction: (fn, body, letBindings = []) => {
        const params = fn.params.length ? `    my (${fn.params.map((p) => `$${p}`).join(", ")}) = @_;\n` : "";
        const lets = letBindings.map(({ name, valueStr }) => `    my $${name} = ${valueStr};`).join("\n");
        const letsBlock = lets ? lets + "\n" : "";
        return `# AUTO-GENERATED by ExprForge -- do not hand-edit.\n` +
               `use strict;\n` +
               `use warnings;\n` +
               `use POSIX ();\n` +
               `use List::Util ();\n\n` +
               `sub ${fn.name} {\n` +
               params +
               letsBlock +
               `    return ${body};\n` +
               `}\n\n` +
               `1;\n`;
    },
    // Multiple named outputs from one call: a plain hash ref (`{ rx => ...,
    // ry => ... }`), Perl's lightest-weight named-record idiom -- no
    // package/class needed just to carry a few doubles back to the caller.
    formatSuite: (fn, outputStrs, letBindings = []) => {
        const params = fn.params.length ? `    my (${fn.params.map((p) => `$${p}`).join(", ")}) = @_;\n` : "";
        const lets = letBindings.map(({ name, valueStr }) => `    my $${name} = ${valueStr};`).join("\n");
        const letsBlock = lets ? lets + "\n" : "";
        const outputNames = Object.keys(outputStrs);
        const fields = outputNames.map((n) => `        ${n} => ${outputStrs[n]},`).join("\n");
        return `# AUTO-GENERATED by ExprForge -- do not hand-edit.\n` +
               `use strict;\n` +
               `use warnings;\n` +
               `use POSIX ();\n` +
               `use List::Util ();\n\n` +
               `sub ${fn.name} {\n` +
               params +
               letsBlock +
               `    return {\n` +
               fields + "\n" +
               `    };\n` +
               `}\n\n` +
               `1;\n`;
    },
});

module.exports = emitter;
