// exprforge/emitters/php.js
const Emitter = require("./base.js");

function fn1(name) {
    return ([x]) => `${name}(${x})`;
}

function fn2(name) {
    return ([a, b]) => `${name}(${a}, ${b})`;
}

// Every variable reference in PHP needs a leading `$` -- unlike every other
// emitter here, base.js's default "var" case (bare `node.name`) is wrong
// for every single reference, not just declarations. Same fix as Perl's
// emitter: override just the one case, defer to the base class otherwise.
class PhpEmitter extends Emitter {
    emitExpr(node) {
        if (node.type === "var") return `$${node.name}`;
        return super.emitExpr(node);
    }
}

const emitter = new PhpEmitter({
    ext: "php",
    // PHP accepts JS-style numeric literal syntax directly, including
    // exponential notation ("1e-9") -- no suffix or conversion needed.
    formatNumber: (v) => String(v),
    calls: {
        sqrt: fn1("sqrt"), abs: fn1("abs"), sin: fn1("sin"), cos: fn1("cos"), tan: fn1("tan"),
        asin: fn1("asin"), acos: fn1("acos"), atan: fn1("atan"), atan2: fn2("atan2"),
        log: fn1("log"), log10: fn1("log10"), exp: fn1("exp"), pow: fn2("pow"),
        floor: fn1("floor"), ceil: fn1("ceil"), round: fn1("round"),
        min: fn2("min"), max: fn2("max"), hypot: fn2("hypot"),
        // log() takes an optional base argument -- covers log2 without a
        // separate function (PHP has no log2() of its own).
        log2: ([x]) => `log(${x}, 2)`,
        // No trunc() anywhere in PHP core. floor for non-negatives, ceil
        // for negatives -- avoids an (int) cast, which would silently
        // misbehave outside PHP's platform integer range.
        trunc: ([x]) => `(${x} >= 0 ? floor(${x}) : ceil(${x}))`,
        // No sign() either -- build it directly. Zero-aware by construction
        // (see Go's/Rust's sign() history in this project for what happens
        // when it isn't).
        sign: ([x]) => `(${x} > 0 ? 1.0 : (${x} < 0 ? -1.0 : 0.0))`,
    },
    // PHP's ?: is exactly base.js's default ternary -- no override needed.
    formatFunction: (fn, body, letBindings = []) => {
        const params = fn.params.map((p) => `$${p}`).join(", ");
        const lets = letBindings.map(({ name, valueStr }) => `    $${name} = ${valueStr};`).join("\n");
        const letsBlock = lets ? lets + "\n" : "";
        return `<?php\n` +
               `// AUTO-GENERATED by ExprForge -- do not hand-edit.\n\n` +
               `function ${fn.name}(${params}) {\n` +
               letsBlock +
               `    return ${body};\n` +
               `}\n`;
    },
    // Multiple named outputs from one call: a plain associative array
    // (`['rx' => ..., 'ry' => ...]`), PHP's lightest-weight named-record
    // idiom -- no class needed just to carry a few doubles back to the
    // caller.
    formatSuite: (fn, outputStrs, letBindings = []) => {
        const params = fn.params.map((p) => `$${p}`).join(", ");
        const lets = letBindings.map(({ name, valueStr }) => `    $${name} = ${valueStr};`).join("\n");
        const letsBlock = lets ? lets + "\n" : "";
        const outputNames = Object.keys(outputStrs);
        const fields = outputNames.map((n) => `        '${n}' => ${outputStrs[n]},`).join("\n");
        return `<?php\n` +
               `// AUTO-GENERATED by ExprForge -- do not hand-edit.\n\n` +
               `function ${fn.name}(${params}) {\n` +
               letsBlock +
               `    return [\n` +
               fields + "\n" +
               `    ];\n` +
               `}\n`;
    },
});

module.exports = emitter;
