// exprforge/emitters/python.js
const Emitter = require("./base.js");

function fn1(name) {
    return ([x]) => `math.${name}(${x})`;
}

function fn2(name) {
    return ([a, b]) => `math.${name}(${a}, ${b})`;
}

function capitalize(s) {
    return s.charAt(0).toUpperCase() + s.slice(1);
}

const emitter = new Emitter({
    ext: "py",
    // Python accepts JS-style numeric literal syntax directly, including
    // exponential notation ("1e-9"), unlike QB64/C# -- no conversion or
    // suffix needed. Integer-valued literals stay Python ints, but that's
    // safe here: every bin op comes from ast.js's own +-*/ set, and
    // Python 3's `/` is always true (float) division regardless of
    // operand types, unlike C#'s int/int trap.
    formatNumber: (v) => String(v),
    calls: {
        sqrt: fn1("sqrt"), abs: ([x]) => `abs(${x})`, sin: fn1("sin"), cos: fn1("cos"), tan: fn1("tan"),
        asin: fn1("asin"), acos: fn1("acos"), atan: fn1("atan"), atan2: fn2("atan2"),
        log: fn1("log"), log2: fn1("log2"), log10: fn1("log10"), exp: fn1("exp"),
        pow: fn2("pow"), min: ([a, b]) => `min(${a}, ${b})`, max: ([a, b]) => `max(${a}, ${b})`,
        hypot: fn2("hypot"),
        // math.floor/ceil/trunc and builtin round() all return int in
        // Python 3, not float -- wrap to stay float64 throughout, matching
        // every other target here, rather than silently switching types.
        floor: ([x]) => `float(math.floor(${x}))`,
        ceil: ([x]) => `float(math.ceil(${x}))`,
        trunc: ([x]) => `float(math.trunc(${x}))`,
        round: ([x]) => `float(round(${x}))`,
        // No math.sign in Python's stdlib -- build it directly. Zero-aware
        // by construction (see Go's/Rust's sign() history in this project
        // for what happens when it isn't).
        sign: ([x]) => `(1.0 if ${x} > 0 else (-1.0 if ${x} < 0 else 0.0))`,
    },
    // Python has no ?: ternary; `a if cond else b` is its conditional
    // expression instead, and it's just as short-circuiting.
    emitSelect: function (condNode, thenStr, elseStr) {
        const L = this.emitExpr(condNode.left);
        const R = this.emitExpr(condNode.right);
        return `(${thenStr} if (${L} ${condNode.op} ${R}) else ${elseStr})`;
    },
    formatFunction: (fn, body, letBindings = []) => {
        const params = fn.params.join(", ");
        const lets = letBindings.map(({ name, valueStr }) => `    ${name} = ${valueStr}`).join("\n");
        const letsBlock = lets ? lets + "\n" : "";
        return `# AUTO-GENERATED by ExprForge -- do not hand-edit.\n` +
               `import math\n\n\n` +
               `def ${fn.name}(${params}):\n` +
               letsBlock +
               `    return ${body}\n`;
    },
    // Multiple named outputs from one call: a small local class (dot
    // access, result.rx) rather than a plain dict -- consistent with
    // every other target here (C/Rust's struct, C#/Go's tuple, Java's
    // nested Result class), and a fixed, self-documenting field set
    // instead of an untyped mapping.
    formatSuite: (fn, outputStrs, letBindings = []) => {
        const params = fn.params.join(", ");
        const lets = letBindings.map(({ name, valueStr }) => `    ${name} = ${valueStr}`).join("\n");
        const letsBlock = lets ? lets + "\n" : "";
        const outputNames = Object.keys(outputStrs);
        const className = `${capitalize(fn.name)}Result`;
        const ctorParams = outputNames.join(", ");
        const ctorAssigns = outputNames.map((n) => `        self.${n} = ${n}`).join("\n");
        const ctorArgs = outputNames.map((n) => outputStrs[n]).join(", ");
        return `# AUTO-GENERATED by ExprForge -- do not hand-edit.\n` +
               `import math\n\n\n` +
               `class ${className}:\n` +
               `    def __init__(self, ${ctorParams}):\n` +
               `${ctorAssigns}\n\n\n` +
               `def ${fn.name}(${params}):\n` +
               letsBlock +
               `    return ${className}(${ctorArgs})\n`;
    },
});

module.exports = emitter;
