// exprforge/emitters/qb64.js
const Emitter = require("./base.js");

const HALF_PI = "1.5707963267948966#";

const emitter = new Emitter({
    ext: "bas",
    formatNumber: (v) => `${v}#`,
    calls: {
        sqrt: ([x]) => `SQR(${x})`,
        abs: ([x]) => `ABS(${x})`,
        sin: ([x]) => `SIN(${x})`,
        cos: ([x]) => `COS(${x})`,
        tan: ([x]) => `TAN(${x})`,
        atan: ([x]) => `ATN(${x})`,
        exp: ([x]) => `EXP(${x})`,
        log: ([x]) => `LOG(${x})`,
        sign: ([x]) => `SGN(${x})`,
        min: ([a, b]) => `_MIN(${a}, ${b})`,
        max: ([a, b]) => `_MAX(${a}, ${b})`,
        round: ([x]) => `_ROUND(${x})`,
        pow: ([base, exp]) => `(${base} ^ ${exp})`,
        asin: ([x]) => `ATN(${x} / SQR(-(${x}) * (${x}) + 1#))`,
        acos: ([x]) => `(${HALF_PI} - ATN(${x} / SQR(-(${x}) * (${x}) + 1#)))`,
        atan2: ([y, x]) => `_ATAN2(${y}, ${x})`,
        log2: ([x]) => `(LOG(${x}) / LOG(2#))`,
        log10: ([x]) => `(LOG(${x}) / LOG(10#))`,
        floor: ([x]) => `INT(${x})`,
        ceil: ([x]) => `(-INT(-(${x})))`,
        trunc: ([x]) => `(SGN(${x}) * INT(ABS(${x})))`,
        hypot: ([a, b]) => `SQR((${a}) * (${a}) + (${b}) * (${b}))`,
    },
    // QB64 has no ternary operator. Comparison operators return -1 (true)
    // or 0 (false), so the algebraically equivalent expression is:
    //   (-1 * then) * cond + else * (1 + cond)
    // cond=-1 (true):  (-1*then)*-1 + else*0 = then
    // cond= 0 (false): (-1*then)* 0 + else*1 = else
    // Both `then` and `else` are always evaluated here (see select()'s
    // doc comment in ast.js) — same as every other target.
    emitSelect: function (condNode, thenStr, elseStr) {
        const L = this.emitExpr(condNode.left);
        const R = this.emitExpr(condNode.right);
        const cond = `(${L} ${condNode.op} ${R})`;
        return `((-1# * ${thenStr}) * ${cond} + ${elseStr} * (1# + ${cond}))`;
    },
    formatFunction: (fn, body, letBindings = []) => {
        const params = fn.params.map((p) => `${p} AS DOUBLE`).join(", ");
        const lets = letBindings
            .map(({ name, valueStr }) => `    Dim ${name}# AS DOUBLE : ${name}# = ${valueStr}`)
            .join("\n");
        const letsBlock = lets ? lets + "\n" : "";
        return `' AUTO-GENERATED by ExprForge -- do not hand-edit.\n` +
               `FUNCTION ${fn.name}# (${params})\n` +
               letsBlock +
               `    ${fn.name}# = ${body}\n` +
               `END FUNCTION\n`;
    },
    // Multiple named outputs from one call: QB64 has no struct/tuple return,
    // so this emits a SUB instead of a FUNCTION, with the outputs as
    // trailing parameters — SUB params are by reference by default in
    // QB64/BASIC, so assigning to them writes back to the caller's
    // variables. This is the classic BASIC multi-output idiom.
    formatSuite: (fn, outputStrs, letBindings = []) => {
        const outputNames = Object.keys(outputStrs);
        const inParams = fn.params.map((p) => `${p} AS DOUBLE`);
        const outParams = outputNames.map((n) => `${n} AS DOUBLE`);
        const lets = letBindings
            .map(({ name, valueStr }) => `    Dim ${name}# AS DOUBLE : ${name}# = ${valueStr}`)
            .join("\n");
        const letsBlock = lets ? lets + "\n" : "";
        const assigns = outputNames.map((n) => `    ${n} = ${outputStrs[n]}`).join("\n");
        return `' AUTO-GENERATED by ExprForge -- do not hand-edit.\n` +
               `SUB ${fn.name} (${[...inParams, ...outParams].join(", ")})\n` +
               letsBlock +
               `${assigns}\n` +
               `END SUB\n`;
    },
});

module.exports = emitter;
