// exprforge/emitters/qb64.js
const Emitter = require("./base.js");

const HALF_PI = "1.5707963267948966#";

const emitter = new Emitter({
    ext: "bas",
    formatNumber: (v) => `${v}#`,
    calls: {
        sqrt: ([x]) => `SQR(${x})`,
        abs: ([x]) => `ABS(${x})`,
        sin: ([x]) => `SIN(${x})`,
        cos: ([x]) => `COS(${x})`,
        tan: ([x]) => `TAN(${x})`,
        atan: ([x]) => `ATN(${x})`,
        exp: ([x]) => `EXP(${x})`,
        log: ([x]) => `LOG(${x})`,
        sign: ([x]) => `SGN(${x})`,
        min: ([a, b]) => `_MIN(${a}, ${b})`,
        max: ([a, b]) => `_MAX(${a}, ${b})`,
        round: ([x]) => `_ROUND(${x})`,
        pow: ([base, exp]) => `(${base} ^ ${exp})`,
        asin: ([x]) => `ATN(${x} / SQR(-(${x}) * (${x}) + 1#))`,
        acos: ([x]) => `(${HALF_PI} - ATN(${x} / SQR(-(${x}) * (${x}) + 1#)))`,
        atan2: ([y, x]) => `_ATAN2(${y}, ${x})`,
        log2: ([x]) => `(LOG(${x}) / LOG(2#))`,
        log10: ([x]) => `(LOG(${x}) / LOG(10#))`,
        floor: ([x]) => `INT(${x})`,
        ceil: ([x]) => `(-INT(-(${x})))`,
        trunc: ([x]) => `(SGN(${x}) * INT(ABS(${x})))`,
        hypot: ([a, b]) => `SQR((${a}) * (${a}) + (${b}) * (${b}))`,
    },
    formatFunction: (fn, body) => {
        const params = fn.params.map((p) => `${p} AS DOUBLE`).join(", ");
        return `' AUTO-GENERATED by ExprForge -- do not hand-edit.\n` +
               `FUNCTION ${fn.name}# (${params})\n` +
               `    ${fn.name}# = ${body}\n` +
               `END FUNCTION\n`;
    },
});

module.exports = emitter;
