// exprforge/emitters/rust.js
//
// Rust's f64 math is method-call syntax (x.sqrt()), not free functions
// (sqrt(x)) like every other target here. The base Emitter's `calls` table
// just holds string templates, so this needs no special-casing in base.js —
// it's the reason `calls` was designed as arbitrary templates instead of a
// plain "language function name" lookup.
const Emitter = require("./base.js");

function method0(name) {
    return ([x]) => `(${x}).${name}()`;
}

function method1(name) {
    return ([recv, arg]) => `(${recv}).${name}(${arg})`;
}

const emitter = new Emitter({
    ext: "rs",
    formatNumber: (v) => (Number.isInteger(v) ? `${v}.0` : String(v)),
    calls: {
        sqrt: method0("sqrt"), abs: method0("abs"), sin: method0("sin"), cos: method0("cos"),
        tan: method0("tan"), asin: method0("asin"), acos: method0("acos"), atan: method0("atan"),
        ln: method0("ln"), log2: method0("log2"), log10: method0("log10"), exp: method0("exp"),
        floor: method0("floor"), ceil: method0("ceil"), round: method0("round"), trunc: method0("trunc"),
        signum: method0("signum"),
        log: method0("ln"),   // Math.log is natural log; Rust spells it ln()
        sign: method0("signum"),
        pow: method1("powf"), atan2: method1("atan2"), min: method1("min"),
        max: method1("max"), hypot: method1("hypot"),
    },
    formatFunction: (fn, body) => {
        const params = fn.params.map((p) => `${p}: f64`).join(", ");
        return `// AUTO-GENERATED by ExprForge -- do not hand-edit.\n` +
               `pub fn ${fn.name}(${params}) -> f64 {\n` +
               `    ${body}\n` +
               `}\n`;
    },
});

module.exports = emitter;
