// exprforge/emitters/typescript.js
//
// Almost identical to js.js at the expression level -- same Math.* calls,
// same number literal syntax, native ternary for select() (no override
// needed) -- since TS numbers are JS numbers. What's different is purely
// surface: typed signatures, ESM `export` instead of CommonJS
// `module.exports` (this targets a frontend build tool, not Node), and a
// named `interface` for multi-output suites instead of an untyped object.
const Emitter = require("./base.js");

function fn1(name) {
    return ([x]) => `Math.${name}(${x})`;
}

function fn2(name) {
    return ([a, b]) => `Math.${name}(${a}, ${b})`;
}

const emitter = new Emitter({
    ext: "ts",
    formatNumber: (v) => String(v),
    calls: {
        sqrt: fn1("sqrt"), abs: fn1("abs"), sin: fn1("sin"), cos: fn1("cos"), tan: fn1("tan"),
        asin: fn1("asin"), acos: fn1("acos"), atan: fn1("atan"), log: fn1("log"),
        log2: fn1("log2"), log10: fn1("log10"), exp: fn1("exp"), floor: fn1("floor"),
        ceil: fn1("ceil"), round: fn1("round"), trunc: fn1("trunc"), sign: fn1("sign"),
        pow: fn2("pow"), atan2: fn2("atan2"), min: fn2("min"), max: fn2("max"), hypot: fn2("hypot"),
    },
    formatFunction: (fn, body, letBindings = []) => {
        const params = fn.params.map((p) => `${p}: number`).join(", ");
        const lets = letBindings.map(({ name, valueStr }) => `    const ${name} = ${valueStr};`).join("\n");
        const letsBlock = lets ? lets + "\n" : "";
        return `// AUTO-GENERATED by ExprForge — do not hand-edit.\n` +
               `export function ${fn.name}(${params}): number {\n` +
               letsBlock +
               `    return ${body};\n` +
               `}\n`;
    },
    // Multiple named outputs from one call: a named interface, returned as
    // an object literal — TS's structural typing means this is checked at
    // every call site, unlike JS's untyped equivalent.
    formatSuite: (fn, outputStrs, letBindings = []) => {
        const params = fn.params.map((p) => `${p}: number`).join(", ");
        const lets = letBindings.map(({ name, valueStr }) => `    const ${name} = ${valueStr};`).join("\n");
        const letsBlock = lets ? lets + "\n" : "";
        const outputNames = Object.keys(outputStrs);
        const interfaceName = `${capitalize(fn.name)}Result`;
        const interfaceFields = outputNames.map((n) => `    ${n}: number;`).join("\n");
        const objectFields = outputNames.map((n) => `        ${n}: ${outputStrs[n]},`).join("\n");
        return `// AUTO-GENERATED by ExprForge — do not hand-edit.\n` +
               `export interface ${interfaceName} {\n${interfaceFields}\n}\n\n` +
               `export function ${fn.name}(${params}): ${interfaceName} {\n` +
               letsBlock +
               `    return {\n${objectFields}\n    };\n` +
               `}\n`;
    },
});

function capitalize(s) {
    return s.charAt(0).toUpperCase() + s.slice(1);
}

module.exports = emitter;
