// exprforge/emitters/typescript.js
//
// Almost identical to js.js at the expression level -- same Math.* calls,
// same number literal syntax, native ternary for select() (no override
// needed) -- since TS numbers are JS numbers. What's different is purely
// surface: typed signatures, ESM `export` instead of CommonJS
// `module.exports` (this targets a frontend build tool, not Node), and a
// named `interface` for multi-output suites instead of an untyped object.
const Emitter = require("./base.js");

function fn1(name) {
    return ([x]) => `Math.${name}(${x})`;
}

function fn2(name) {
    return ([a, b]) => `Math.${name}(${a}, ${b})`;
}

const emitter = new Emitter({
    ext: "ts",
    formatNumber: (v) => String(v),
    calls: {
        sqrt: fn1("sqrt"), abs: fn1("abs"), sin: fn1("sin"), cos: fn1("cos"), tan: fn1("tan"),
        asin: fn1("asin"), acos: fn1("acos"), atan: fn1("atan"), log: fn1("log"),
        log2: fn1("log2"), log10: fn1("log10"), exp: fn1("exp"), floor: fn1("floor"),
        ceil: fn1("ceil"), trunc: fn1("trunc"), sign: fn1("sign"),
        // See js.js's own comment -- same fix, same reasoning, same
        // runtime (Math.*).
        round: ([x]) => `(Math.sign(${x}) * Math.floor(Math.abs(${x}) + 0.5))`,
        pow: fn2("pow"), atan2: fn2("atan2"), min: fn2("min"), max: fn2("max"), hypot: fn2("hypot"),
        wrapIndex: ([i, m]) => `(((${i} % ${m}) + ${m}) % ${m})`,
        clampIndex: ([i, lo, hi]) => `Math.max(${lo}, Math.min(${hi}, ${i}))`,
    },
    // "number[]" for an array-typed param (see ast.js's paramTypes
    // comment), "number" for every ordinary scalar -- array.length
    // exists natively, so no separate count-parameter workaround is
    // needed here the way QB64/C/Fortran need one.
    emitIndex: function (targetNode, atNode) {
        return `${this.emitExpr(targetNode)}[${this.emitExpr(atNode)}]`;
    },
    // Opt-in only (see emitFunction's `addTypeGuards` and
    // docs/runtime-type-guards.md) -- TS's `number[]` annotation is
    // erased at compile time and enforced only against a caller who is
    // ALSO type-checked by tsc; a plain JS caller, an `any`/unsafe cast,
    // or a value crossing a JSON/network boundary all bypass it
    // entirely, so this is a real runtime backstop, not a redundant one.
    typeGuard: (p, fnName) => `if (!Array.isArray(${p})) throw new Error(${JSON.stringify(`${fnName}: "${p}" must be an array`)});`,
    formatFunction: (fn, body, letBindings = [], guardLines = []) => {
        const params = fn.params.map((p) => `${p}: ${fn.paramTypes?.[p] === "number[]" ? "number[]" : "number"}`).join(", ");
        const guards = guardLines.map((l) => `    ${l}`).join("\n");
        const guardsBlock = guards ? guards + "\n" : "";
        const lets = letBindings.map(({ name, valueStr }) => `    const ${name} = ${valueStr};`).join("\n");
        const letsBlock = lets ? lets + "\n" : "";
        return `// AUTO-GENERATED by ExprForge — do not hand-edit.\n` +
               `export function ${fn.name}(${params}): number {\n` +
               guardsBlock +
               letsBlock +
               `    return ${body};\n` +
               `}\n`;
    },
    // Multiple named outputs from one call: a named interface, returned as
    // an object literal — TS's structural typing means this is checked at
    // every call site, unlike JS's untyped equivalent.
    formatSuite: (fn, outputStrs, letBindings = [], guardLines = []) => {
        const params = fn.params.map((p) => `${p}: ${fn.paramTypes?.[p] === "number[]" ? "number[]" : "number"}`).join(", ");
        const guards = guardLines.map((l) => `    ${l}`).join("\n");
        const guardsBlock = guards ? guards + "\n" : "";
        const lets = letBindings.map(({ name, valueStr }) => `    const ${name} = ${valueStr};`).join("\n");
        const letsBlock = lets ? lets + "\n" : "";
        const outputNames = Object.keys(outputStrs);
        const interfaceName = `${capitalize(fn.name)}Result`;
        const interfaceFields = outputNames.map((n) => `    ${n}: number;`).join("\n");
        const objectFields = outputNames.map((n) => `        ${n}: ${outputStrs[n]},`).join("\n");
        return `// AUTO-GENERATED by ExprForge — do not hand-edit.\n` +
               `export interface ${interfaceName} {\n${interfaceFields}\n}\n\n` +
               `export function ${fn.name}(${params}): ${interfaceName} {\n` +
               guardsBlock +
               letsBlock +
               `    return {\n${objectFields}\n    };\n` +
               `}\n`;
    },
});

function capitalize(s) {
    return s.charAt(0).toUpperCase() + s.slice(1);
}

module.exports = emitter;
